insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (1, 'pollo al horno', '1200', false, true, false, true);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (2, 'carne asada', '1800', false, true, false, true);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (3, 'te con leche', '150', true, false, true, false);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (4, '2 naranjas', '300', true, false, true, false);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (5, 'canelones de verduras', '1000', false, true, false, true);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (6, 'papa al horno', '1200', false, true, false, true);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (7, 'milanesa a la napolitana', '1300', false, true, false, true);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (8, 'pescado a la crema', '800', false, true, false, true);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (9, 'chinchulines al limon', '2000', false, true, false, true);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (10, 'ravioles al verdeo', '900', false, true, false, true);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (11, 'bomba de papa', '700', false, true, false, true);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (12, '4 tostadas con dulce de leche', '600', true, false, true, false);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (13, 'milanesa de zukini', '800', false, true, false, true);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (14, 'sorrentinos de calabaza', '1400', false, true, false, true);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (15, 'cafe con leche', '300', true, false, true, false);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (16, '2 kiwis', '300', true, false, true, false);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (17, 'pechito de cerdo', '2000', false, true, false, true);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (18, 'pure de papas', '700', false, true, false, true);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (19, 'ensalada rusa', '600', false, true, false, true);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (20, 'arroz con pollo', '1600', false, true, false, true);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (21, '3 chorizos', '1400', false, true, false, true);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (22, '2 morcillas', '1100', false, true, false, true);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (23, 'pollo', '1100', false, true, false, true);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (24, 'papas', '1100', false, true, false, true);
insert into plate (id, name, calories, breakfast, lunch, supper, dinner) values (25, 'peras', '1100', false, true, false, true);

insert into diet (name, score, breakfast, lunch, supper, dinner) values ('hiper', '2200', 1, 2, 3, 4);
insert into diet (name, score, breakfast, lunch, supper, dinner) values ('hipo', '1800', 5, 6, 7, 8);
