insert into word (id, name, definition) values (1, 'Camaro1', 'Vehiculo deportivo');
insert into word (id, name, definition) values (2, 'Camaro2', 'Vehiculo deportivo');
insert into word (id, name, definition) values (3, 'Camaro3', 'Vehiculo deportivo');
insert into word (id, name, definition) values (4, 'Camaro4', 'Vehiculo deportivo');
insert into word (id, name, definition) values (5, 'Camaro5', 'Vehiculo deportivo');
insert into word (id, name, definition) values (6, 'Camaro6', 'Vehiculo deportivo');
insert into word (id, name, definition) values (7, 'Camaro7', 'Vehiculo deportivo');
insert into word (id, name, definition) values (8, 'Camaro8', 'Vehiculo deportivo');
insert into word (id, name, definition) values (9, 'Camaro9', 'Vehiculo deportivo');